name: custom_neumorphic
description: Custom Neumorphic is a flutter package provide neumorphism ui kit.
version: 0.0.1-beta
homepage: https://linktr.ee/arfaz_860
repository: https://github.com/Arfaz123/custom_neumorphic.git
topics: [ui-kit, custom-neumorphic, neumorphism]

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

